// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIZuhUKbaVeIfLCCSnW-3SAkcI4-H11dA',
    appId: '1:1076247310676:web:0c15f5909b4d6765a5d8c1',
    messagingSenderId: '1076247310676',
    projectId: 'sustainable-guide',
    authDomain: 'sustainable-guide.firebaseapp.com',
    storageBucket: 'sustainable-guide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNt69U7dfGzypHmfd3HZ8qR25Zort3u4w',
    appId: '1:1076247310676:android:d9f7de186cc9cd5da5d8c1',
    messagingSenderId: '1076247310676',
    projectId: 'sustainable-guide',
    storageBucket: 'sustainable-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxpGxOV-lj4jrCyBKhTOyDI4yUYK4omls',
    appId: '1:1076247310676:ios:750f263b6498ec98a5d8c1',
    messagingSenderId: '1076247310676',
    projectId: 'sustainable-guide',
    storageBucket: 'sustainable-guide.firebasestorage.app',
    iosClientId: '1076247310676-ipfv9jidpvldqa003kbrhq9ipagp27rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxpGxOV-lj4jrCyBKhTOyDI4yUYK4omls',
    appId: '1:1076247310676:ios:750f263b6498ec98a5d8c1',
    messagingSenderId: '1076247310676',
    projectId: 'sustainable-guide',
    storageBucket: 'sustainable-guide.firebasestorage.app',
    iosClientId: '1076247310676-ipfv9jidpvldqa003kbrhq9ipagp27rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF72q11-TnaUgfHX11HIKlE4LqNrcBpaE',
    appId: '1:1076247310676:web:6c2a038f24a0b06aa5d8c1',
    messagingSenderId: '1076247310676',
    projectId: 'sustainable-guide',
    authDomain: 'sustainable-guide.firebaseapp.com',
    storageBucket: 'sustainable-guide.firebasestorage.app',
  );
}
